// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVeTRAQQgLUK_CAiEtUexa9titpA_WDQ',
    appId: '1:826009346463:web:278e8a5c8dcc42f4ca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    authDomain: 'usuarios-byr-uge.firebaseapp.com',
    databaseURL: 'https://usuarios-byr-uge-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-byr-uge.firebasestorage.app',
    measurementId: 'G-M30DF4RPRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIHnwWFpLWPr8AzirUoS5EmKBQHVag7xQ',
    appId: '1:826009346463:android:b68f37ce041fcececa5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    databaseURL: 'https://usuarios-byr-uge-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-byr-uge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZokHf7ttwST8aTCrkq-lCTel6zsljM3w',
    appId: '1:826009346463:ios:f7cfac06a3ba80b7ca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    databaseURL: 'https://usuarios-byr-uge-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-byr-uge.firebasestorage.app',
    iosBundleId: 'com.example.appuge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZokHf7ttwST8aTCrkq-lCTel6zsljM3w',
    appId: '1:826009346463:ios:f7cfac06a3ba80b7ca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    databaseURL: 'https://usuarios-byr-uge-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-byr-uge.firebasestorage.app',
    iosBundleId: 'com.example.appuge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyVeTRAQQgLUK_CAiEtUexa9titpA_WDQ',
    appId: '1:826009346463:web:03c76998cca69735ca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    authDomain: 'usuarios-byr-uge.firebaseapp.com',
    databaseURL: 'https://usuarios-byr-uge-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-byr-uge.firebasestorage.app',
    measurementId: 'G-F28RY9MQH6',
  );
}
